- docker-compose.yml
- lib/http.py
- lib/queue/processor.py
- lib/queue/queue.py
- lib/queue/worker.py
References 3852 in Jira - 
During the last deploy we had to rush in a fix to presto that would add a `QUEUE_PREFIX` environment variable so that we could have differently named SQS queues for the QA and Live environments. This came into conflict with the existing way we check for environment settings, where we opt to use a local value first by default. Our tests were broken as a result, since there's no local QUEUE_PREFIX supplied by default. I went ahead and added fixes to unify the calling for this `QUEUE_PREFIX` setting, and set it up to use the environment variable for it by default. This should fix the issues and clean up the incongruencies we had this week.
> CV2-3852 fix queue prefix logic

- README.md
- lib/model/video.py
- lib/schemas.py
In preparation for adding video / to check-api alegre integration
> Change keys for presto video response

- lib/queue/queue.py
This bugfix ensures that the `.fifo` suffix is appended to the end of output queues as well as input queue names.
There are no security concerns with this change that I can conceive of.
> Ensure that fifo suffix comes at end of output queue names.

- lib/queue/processor.py
- lib/queue/queue.py
- lib/queue/worker.py
This fixes a few more issues with FIFO queue names in presto.
There should be no security concerns associated with these modifications.
Logic was tested in QA where actual SQS queues and permissions are available for proper execution.
> Refactor the FIFO queue naming logic.

- lib/s3.py
Use default role based access for S3 instead of explicit credentials.
> Use default role based access for S3 instead of explicit credentials.

- lib/queue/queue.py
- lib/queue/worker.py
- lib/sentry.py
- test/lib/queue/test_processor.py
- test/lib/queue/test_queue.py
Adds retry logic and dead letter message dumping when retries are exhausted
> CV2-4606 Add retry logic and dead letter message dumping

- lib/queue/worker.py
- lib/schemas.py
- test/lib/queue/test_queue.py
Right now when we increment retry count it actually doesn't do anything, because it silently gets dropped when parsing the message into the schema - we need this in order to properly increment and ultimately fail
> CV2-4606 add retry count to spec

- lib/queue/queue.py
- lib/queue/worker.py
If we don't delete the existing message this code just has the net effect of *compounding the same task repeatedly* which is definitely not what we want! Increment the count, delete the old job, and add a new job.
> Cv2 4606 delete message

- lib/telemetry.py
- test/lib/test_telemetry.py
As per discussion with @skyemeedan we're trying to isolate why Presto hemorrhages opentelemetry timeouts but timpani doesn't - one diff is this timeout count so removing that as a variable.
Reference: CV2-4725
Tested the parsing of a non value and works fine
none
none
> CV2-4725 decrease timeout on telemetry pings from 60s to 10s

- .env_file.example
- .env_file.test
- docker-compose.yml
- lib/cache.py
- lib/model/model.py
- lib/schemas.py
- lib/telemetry.py
- requirements.txt
- test/lib/model/test_video.py
- test/lib/queue/test_queue.py
- test/lib/test_cache.py
Adds a redis caching layer to presto to optionally bypass the fingerprinting routine for already-fingerprinted items. Also adds ability to flexibly define ttl and optionally bypass that.
Reference: CV2-4719
Not yet tested locally - will do integration testing once unit tests passing on all three services
Adds redis - will need to make sure we can access it with @sonoransun 
Nothing particularly interesting here
> CV2-4719 initial idea saround caching layer in presto

- Dockerfile
- docker-compose.yml
- lib/queue/processor.py
- requirements.txt
- start_all.sh
Pin all pip install versions to reduce dependency thrashing
Reference: CV2-4855
Not tested locally - need to watch CI to see if it just builds at all with these changes, or if we had these installs outside the requirements.txt for a reason
None
None
> CV2-4855 move Dockerfile requirements to requirements.txt

- extra/callback_server.py
Simple python code for a callback server that spins up on an input port (9888 by default) and receives and prints post requests, which can be used as the callback server for testing/debugging presto locally.
Reference: TICKET-ID (to provide additional context)
[CV2-4978](https://meedan.atlassian.net/browse/CV2-4978)
Has it been tested locally? Are there automated tests?
This has been tested while developing classycat in presto and works fine
No
Only use this locally, not to be used in production or security sensitive use cases
[CV2-4978]: https://meedan.atlassian.net/browse/CV2-4978?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CV2-4978: Local callback server for receiving presto callback responses

- lib/model/classycat_classify.py
- test/lib/model/test_classycat.py
Code and tests for verifying the returned labels belong to the same set as defined in the classycat schema.
In case some items in a batch have out-of-schema labels, those items will be omitted from the results, however the rest of items that were classified as expected will be returned. In case all the generated labels are out of schema, an error will be returned, marking the operation as failure.
Reference: [CV2-4801](https://meedan.atlassian.net/jira/software/c/projects/CV2/issues/CV2-4801)
Has been tested locally and through unit tests.
However the condition where LLM returns out of schema labels is difficult to control and reproduce.
But the scenario has been reproduced in unit tests and it's verified the code functions as expected in case of out of schema labels.
This code requires …
> double check returned categories to make sure they are in-schema + tests

- lib/base_exception.py
- lib/model/classycat.py
- lib/model/classycat_classify.py
- lib/model/classycat_schema_create.py
- lib/model/classycat_schema_lookup.py
- lib/model/model.py
- lib/queue/processor.py
- test/lib/model/test_classycat.py
Error handling for ClassyCat using new error handling / exception mechanisms in Presto
ClassyCat modules now raise unhandled "PrestoBaseException" objects that include an http error code to properly respond to consumer requests.
Reference: [CV2-4952](https://meedan.atlassian.net/jira/software/c/projects/CV2/issues/CV2-4952)
Has been tested locally and in unit tests
No
We return stack traces included in error messages, which raises security concerns.
[CV2-4952]: https://meedan.atlassian.net/browse/CV2-4952?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CV2-4952: ClassyCat Error Handling and Metrics

- lib/model/generic_transformer.py
- test/lib/model/test_generic.py
Brings text errors back in line with other fingerprinting errors
Reference: CV2-5101
Not yet tested locally
No dependency change
No security change.
> CV2-5101 i think you can just.... delete the subclass function and it'll just work?

- lib/model/yake_keywords.py
- requirements.txt
- test/lib/model/test_yake_keywords.py
applying the following to improve yake keywords extraction 
1- Replace ’ with ' and similar for other characters
2- Keep the longest keyword of if there is an overlap between two keywords. (“good” and “good morning” keep “good morning”) 
3- If language is not specified or is “auto” perform language detection with CLD
Reference: CV2-4909 (to provide additional context)
locally + already existing tests
> adding auto langdetect and cleaning up keywords extracted by yake

- lib/model/yake_keywords.py
- requirements.txt
- test/lib/model/test_yake_keywords.py
using jieba to segment mandarin text
Reference: CV2-5247 and CV2-4909
Has it been tested locally? Are there automated tests?
locally. will add automated tests as well. 
Are there changes required in sysops terraform for this feature or fix?
Please list any security concerns that may be relevant.
> CV2-5247-support-yake-keyword-extraction-for-chinese

- lib/model/generic_transformer.py
Minor tweak to make text work
Reference: CV2-5370
Tested locally extensively and confirmed to work!
Likely no.
None.
> Cv2 5370 media text split

- lib/model/generic_transformer.py
- lib/model/model.py
Adds additional context dict to inject function-level context if/when valuable to reproduce specific errors
Reference: CV2-5050
Tested in QA and confirmed to pipe the correct data through to sentry
None
None
> CV2-5050 add additional context when transformer vectorization fails

- lib/queue/queue.py
- test/lib/queue/test_processor.py
- test/lib/queue/test_queue.py
Queues could theoretically get wonky with long-held state, and also we could be more specific when selecting queues by using singular access instead of filters.
Not tested locally yet
Nothing changes in this PR
Nothing changes in this PR
> refactor to get rid of persistent queues and change to singular lookup

- lib/queue/processor.py
- test/lib/queue/test_processor.py
Adds 30s timeout and some logs to help diagnose long running callbacks
Not tested locally
Nope!
None
> CV2-5589 add explicit timeout

- lib/queue/processor.py
- lib/queue/queue.py
- lib/queue/worker.py
- test/lib/queue/test_queue.py
Responding to more issues where we fail to pickup queues under threaded environments. More work to make it threadsafe
Tested locally and continues to work!
No change
No Change
> CV2-5589 More support for queuing under threaded environments

- lib/queue/queue.py
- test/lib/queue/test_queue.py
More problems downstream.. need better test coverage here.
Re-ran locally to fix broken tests
None
None
> Cv2 5589 singular queues downstream

- lib/queue/queue.py
- test/lib/queue/test_queue.py
Reverts regression on structure of receive_messages which returns tuples, and changed as a result of moving to singular queue responses
Tests confirm this was a regression - other tests really should have caught this outside just the singular case
None
None
> CV2-5589 reverts accidental regression

- lib/queue/queue.py
- test/lib/queue/test_queue.py
More knock-ons of bad test mocks and switchover from multi stateful to single stateless
Worked through the current issue on sentry locally and confirmed this will return a queue properly
None
None
> CV2-5589 resolve broken requests to delete messages

- start_all.sh
Re-adding http after tests confirming http seems to thrash the box
Reference: CV2-5709
None
None
None
> CV2-5709 readd http condition only for non-workers

- start_all.sh
Wraps processor (which is the _other_ "listening to queues..." functionality) to only run on worker instances
Reference: CV2-5709
none
none
none
> CV2-5709 wrap processor run within worker status check

- start_all.sh
Bug fix for not running worker or processor when running Presto in server role.
Reference: CV2-5119
Tested locally
No security concerns with this change.
> Bugfix on start script to ensure we do not run worker or processor in server role tasks

- lib/queue/queue.py
We hemorrhage a ton of `EmptyReceives` when requesting messages via SQS - this PR slows down the requestor to an amount that is negligible for us, but will greatly reduce ridiculous levels of needless spend.
Reference: CV2-5639
By its nature this is a remote/cloud issue
none
none
> CV2-5639 add sleep during message receives

- lib/model/generic_transformer.py
- lib/model/model.py
- lib/queue/queue.py
- test/lib/queue/test_queue.py
We have some errors where we're attempting to vectorize texts where the "texts" are null. We have no provenance tracking for how these filtered into Presto. In order to debug this effectively, we need to know that info - and for many other errors that'll likely be the case as well. This packs in additional context to sentry captures for any fingerprinting process.
Reference: CV2-5789
Not yet tested locally - we already have this pattern in place for a few cases so it _should_ just play nicely.
None, sentry I suppose, lol
Nothing in particular here.
> CV2-5789 pack in more context for error states on presto

- .github/workflows/ci-test-pr.yml
- lib/queue/processor.py
- lib/queue/worker.py
- lib/s3.py
- lib/sentry.py
- requirements.txt
- test/lib/queue/test_processor.py
- test/lib/queue/test_queue.py
When you run `logger.error` in the context of an exception, that percolates to sentry as an error with whatever the `logger.error` text is. This converts those cases to use our capture message format instead to sync them all up.
Reference: CV2-5925
Not yet tested locally, CI should discover any issues here.
None
Not relevant
> [CV2-5925] standardize messages for logs
